### ISSUE TITLE
It seems that this mod crashed my modded smp server on server start-up

### ISSUE THREAD

**Issue by Dyshonored** [Bomb787/MoGuns-Addon#1]
Here is the crash report 
The mod works fine with the same modpack in single player.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/11/21 10:42 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forgeserver.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forgeserver.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forgeserver.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forgeserver.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forgeserver.jar:36.2] {}
-- MOD moguns --
Details:
	Mod File: MoGuns-1.2-1.16.5.jar
	Failure message: Mo' Guns (moguns) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
	Mod Version: 1.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forgeserver.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_202] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_202] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_202] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_202] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_202] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_202] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_202] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3356540768 bytes (3201 MB) / 4206362624 bytes (4011 MB) up to 4206362624 bytes (4011 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forgeserver.jar object_holder_definalize PLUGINSERVICE 
		/forgeserver.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forgeserver.jar capability_inject_definalize PLUGINSERVICE 
		/forgeserver.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forgeserver.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.4
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		Zombie+Extreme+1.16.5+1.8.2.jar                   |Zombie Extreme                |zombie_extreme                |1.8.2               |CREATE_REG|Manifest: NOSIGNATURE
		UnionLib-1.16.5-3.3.7.jar                         |UnionLib                      |unionlib                      |3.3.7               |CREATE_REG|Manifest: NOSIGNATURE
		primalwinter-forge-1.16.4-2.0.7.jar               |Primal Winter                 |primalwinter                  |2.0.7               |CREATE_REG|Manifest: NOSIGNATURE
		mobbattle-1.16.5-2.3.7.jar                        |Mob Battle Mod                |mobbattle                     |1.16.5-2.3.7        |CREATE_REG|Manifest: NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		crafting-dead-core-1.16.5-1.7.5-alpha.jar         |Crafting Dead                 |craftingdead                  |1.7.5-alpha         |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.129.jar                          |Just Enough Items             |jei                           |7.7.1.129           |CREATE_REG|Manifest: NOSIGNATURE
		incontrol-1.16-5.2.2.jar                          |InControl                     |incontrol                     |1.16-5.2.2          |CREATE_REG|Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.22.449.jar                   |Mekanism                      |mekanism                      |10.0.22             |CREATE_REG|Manifest: NOSIGNATURE
		autooredictconv-1.16.4-16.1.10.jar                |Auto Ore Dictionary Converter |autooredictconv               |16.1.10             |CREATE_REG|Manifest: NOSIGNATURE
		MoGuns-1.2-1.16.5.jar                             |Mo' Guns                      |moguns                        |1.0                 |ERROR     |Manifest: NOSIGNATURE
		BetterPortals-1.16.4-0.3.8.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.8        |CREATE_REG|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		EnhancedVisuals_v1.3.32_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		Controlling-7.0.0.27.jar                          |Controlling                   |controlling                   |7.0.0.27            |CREATE_REG|Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.3.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.3      |CREATE_REG|Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |CREATE_REG|Manifest: NOSIGNATURE
		configured-1.2.0-1.16.3.jar                       |Configured                    |configured                    |1.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |CREATE_REG|Manifest: NOSIGNATURE
		additional-guns-0.3.0-1.16.5.jar                  |Additional Guns               |additionalguns                |0.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		champions-forge-1.16.5-2.0.1.7.jar                |Champions                     |champions                     |1.16.5-2.0.1.7      |CREATE_REG|Manifest: NOSIGNATURE
		mdecore-1.16.4-16.1.0.jar                         |MattDahEpic Core              |mdecore                       |16.1.0              |CREATE_REG|Manifest: NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |CREATE_REG|Manifest: d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.7.jar                             |Tips                          |tips                          |4.0.7               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BadMobs-1.16.5-9.0.3.jar                          |BadMobs                       |badmobs                       |9.0.3               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		crafting-dead-survival-1.16.5-1.1.8-alpha.jar     |Crafting Dead Survival        |craftingdeadsurvival          |1.1.8-alpha         |CREATE_REG|Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.22.449.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.22             |CREATE_REG|Manifest: NOSIGNATURE
		catalogue-1.3.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.2.455.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.455           |CREATE_REG|Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-7.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-7             |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-universal.jar                 |Forge                         |forge                         |36.2.4              |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		VendingMachine-1.16.2-1.0.0.6.jar                 |Vending Machine               |vm                            |1.0.0.6             |CREATE_REG|Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.16.5-1.2.0.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.1.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.1        |CREATE_REG|Manifest: NOSIGNATURE
		torchmaster-2.3.8.jar                             |Torchmaster                   |torchmaster                   |2.3.8               |CREATE_REG|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.5-140.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.5-140    |CREATE_REG|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		Geolosys-1.16.5-5.1.5.jar                         |Geolosys                      |geolosys                      |5.1.5               |CREATE_REG|Manifest: NOSIGNATURE
		Fallout+Inspired+Power+Armor+0.7.jar              |Power armor                   |fallout_inspired_power_armor  |0.3                 |CREATE_REG|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal (1).jar |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |CREATE_REG|Manifest: NOSIGNATURE
		ShoulderSurfing-1.16.5-2.2.1.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.5-2.2.1        |CREATE_REG|Manifest: NOSIGNATURE
		Futurepack-1.16.5-31.2.6976.jar                   |Futurepack                    |futurepack                    |31.2.6976           |CREATE_REG|Manifest: 78:ee:c7:a4:2b:54:18:c6:71:6a:84:82:fa:d9:98:5a:a8:33:83:96:b1:4b:e6:1a:c9:56:58:d7:e8:92:1d:63
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		lycanitesmobs-1.16.5-2.3.3.3.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.3.3      |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |CREATE_REG|Manifest: NOSIGNATURE
		Xaeros_Minimap_21.21.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.21.0             |CREATE_REG|Manifest: NOSIGNATURE
		diet-forge-1.16.5-1.0.0.jar                       |Diet                          |diet                          |1.16.5-1.0.0        |CREATE_REG|Manifest: NOSIGNATURE
		collective-1.16.5-2.64.jar                        |Collective                    |collective                    |2.64                |CREATE_REG|Manifest: NOSIGNATURE
		mobsunscreen-1.16.5-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.16.5-3.0.4        |CREATE_REG|Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.16.4-1.5.1.jar          |Better Third Person           |betterthirdperson             |1.5.1               |CREATE_REG|Manifest: NOSIGNATURE
		backpacked-1.10.1-1.16.3.jar                      |Backpacked                    |backpacked                    |1.10.1              |CREATE_REG|Manifest: NOSIGNATURE
		backpacker-1.3.1-1.16.3.jar                       |Backpacker                    |backpacker                    |1.3.1               |CREATE_REG|Manifest: NOSIGNATURE
		lostcities-1.16-4.0.10-beta.jar                   |LostCities                    |lostcities                    |1.16-4.0.10-beta    |CREATE_REG|Manifest: NOSIGNATURE
		Survive-1.16.5-3.4.4.jar                          |Survive                       |survive                       |1.16.5-3.4.4        |CREATE_REG|Manifest: NOSIGNATURE
		simplytea-1.16.5-2.4.0.jar                        |Simply Tea                    |simplytea                     |2.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |CREATE_REG|Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		tiered-1.16.5-1.2.3-forge-beta.jar                |Tiered                        |tiered                        |1.16.5-1.2.3-forge-b|CREATE_REG|Manifest: NOSIGNATURE
		starterkit_1.16.5-2.5.jar                         |Starter Kit                   |starterkit                    |2.5                 |CREATE_REG|Manifest: NOSIGNATURE
		increasemobcap-forge-1.16.2-1.0.1.jar             |Increase Mob Cap              |increasemobcap                |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		nethers_delight-2.1.jar                           |Nethers Delight               |nethers_delight               |2.1                 |CREATE_REG|Manifest: NOSIGNATURE
		mutantmore-1.16.5-1.0.0.jar                       |Mutant More                   |mutantmore                    |1.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		enhancedcelestials-2.0.8-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.8-1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		farmerstea-1.16.5-1.3.jar                         |Farmer's Tea - A Compat Mod   |farmerstea                    |1.16.5-1.3          |CREATE_REG|Manifest: NOSIGNATURE
		PlayerRevive_v2.0.0-pre04_mc1.16.5.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.50.jar                  |GeckoLib                      |geckolib3                     |3.0.50              |CREATE_REG|Manifest: NOSIGNATURE
		OpenLoader-1.16.5-9.0.2.jar                       |OpenLoader                    |openloader                    |9.0.2               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
	Crash Report UUID: 39a606ab-104a-4572-831f-024963ad69be

**Comment by Dyshonored** [comment]
Just in case it helps, the forge version I'm running is 36.2.4
