### ISSUE TITLE
server does not start

### ISSUE THREAD

**Issue by Scorpion2202** [Bomb787/MoGuns-Addon#4]
The server with your mod does not start, can you help to solve this problem?
Here are the logs
https://www.toptal.com/developers/hastebin/xuhideroda
/\ "-./  \ /\  __ \ /\ \_\ \ /\ \ /\  ___\ /\__  _\ 
\ \ \-./\ \\ \ \/\ \\ \  __ \\ \ \\ \___  \\/_/\ \/ 
 \ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\  \ \_\ 
  \/_/  \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/   \/_/ 
                                                    

                                      Welcome to Mohist 1.16.5 ! - Mohist Developement Group - 1.16.5-1038, Java 55.0
Checking libraries, please wait...
All libraries are nice :) !
Checking the installation, please wait.
Finished the install verification process !
[03:21:44 INFO]: Update in check...
[03:21:44 INFO]: If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
[03:21:44 INFO]: No update found, latest version: (1.16.5-1038) current version: (1.16.5-1038)
[03:21:44 INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.mohistVersion, 1038, --fml.forgeVersion, 36.2.39, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, com.mohistmc, nogui]
[03:21:44 INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 11.0.6 by Oracle Corporation
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/container/libraries/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[03:21:44 INFO]: Added Lets Encrypt root certificates as additional trust
[03:21:45 INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/container/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[03:21:48 INFO]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[03:22:03 INFO]: Forge mod loading, version 36.2.39, for MC 1.16.5 with MCP 20210115.111550
[03:22:03 INFO]: MinecraftForge v36.2.39 Initialized
[03:22:03 INFO]: EventDispatcherRegistry initialized
[03:22:06 INFO]: [moguns.MoGuns:setup:100]: MoGuns preinit, if you're reading this then I hope you're having a nice day :)
[03:22:14 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:22:15 INFO]: Reloading ResourceManager: Default, mohist-1.16.5-1038-universal.jar, bukkit, obfuscate-0.6.3-1.16.5.jar, cgm-1.2.6-1.16.5.jar, WeaponThrow-1.16.4-5.7.jar, tac-r-0.2.0-1.16.5.jar, TaxOceanVillager+1.16.5+Modi+1.0.1.jar, MoGuns-1.6-1.16.5.jar
[03:22:18 WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 757 path $.modules.zoom
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:198) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist-1.16.5-1038-server.jar:36.2]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-8.1.3.jar:?]
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:119) ~[mohist-1.16.5-1038-server.jar:?]
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:116) ~[mohist-1.16.5-1038-server.jar:?]
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:100) ~[mohist-1.16.5-1038-server.jar:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 757 path $.modules.zoom
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?]
        at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?]
        at com.mrcrayfish.guns.common.NetworkGunManager.lambda$null$4(NetworkGunManager.java:85) ~[cgm:1.2.6-1.16.5]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at com.mrcrayfish.guns.common.NetworkGunManager.lambda$prepare$5(NetworkGunManager.java:74) ~[cgm:1.2.6-1.16.5]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.mrcrayfish.guns.common.NetworkGunManager.prepare(NetworkGunManager.java:64) ~[cgm:1.2.6-1.16.5]
        at com.mrcrayfish.guns.common.NetworkGunManager.func_212854_a_(NetworkGunManager.java:44) ~[cgm:1.2.6-1.16.5]
        at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 757 path $.modules.zoom
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[server-1.16.5-20210115.111550-extra.jar:?]
        at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?]
        at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?]
        at com.mrcrayfish.guns.common.NetworkGunManager.lambda$null$4(NetworkGunManager.java:85) ~[cgm:1.2.6-1.16.5]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at com.mrcrayfish.guns.common.NetworkGunManager.lambda$prepare$5(NetworkGunManager.java:74) ~[cgm:1.2.6-1.16.5]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.mrcrayfish.guns.common.NetworkGunManager.prepare(NetworkGunManager.java:64) ~[cgm:1.2.6-1.16.5]
        at com.mrcrayfish.guns.common.NetworkGunManager.func_212854_a_(NetworkGunManager.java:44) ~[cgm:1.2.6-1.16.5]
        at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Hosting-Minecraft : Сервер отмечен как offline...

Hosting-Minecraft ---------- Панель управления обнаружила падения сервера! ----------
Hosting-Minecraft ---------- Ошибка по которой это произошло, написана выше! ----------
Hosting-Minecraft Exit code: 0
Hosting-Minecraft Out of memory: false
Hosting-Minecraft Проверка использования дискового пространства сервера, это может занять несколько секунд...
Hosting-Minecraft Обновление файлов конфигурации процесса...
Hosting-Minecraft Проверка и установка прав доступа к файлам, это может занять несколько секунд...
Hosting-Minecraft : Сервер отмечен как starting...
Hosting-Minecraft Получение образа контейнера сервера, это может занять несколько секунд...
Hosting-Minecraft Завершено получение образа контейнера.

**Comment by Bomb787** [comment]
Mohist breaks many mods, so we don't support it. You're gonna have to either remove the mod or use something other than Mohist.
